export const substanceList = [
  //Combinations are not accurate with actuals facts(needs update)
  {
    id: 1,
    name: "Cannabis",
    active: false,
    combinations: {
      2: "Synergy",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 2,
    name: "LSD",
    active: false,
    combinations: {
      1: "Synergy",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 3,
    name: "Cocaine",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 4,
    name: "MDMA",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Synergy",
      3: "Caution",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 5,
    name: "Amphetamines",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 6,
    name: "Ketamine",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 7,
    name: "NBOme",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 8,
    name: "Mushrooms",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 9,
    name: "Mescaline",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 10,
    name: "DMT",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 11,
    name: "2C-B",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 12,
    name: "Benzodiazepines",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 13,
    name: "Cafeine",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 14,
    name: "GHB",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 15,
    name: "Opioids",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
  {
    id: 16,
    name: "Alcohol",
    active: false,
    combinations: {
      1: "Synergy",
      2: "Caution",
      3: "Caution",
      4: "Synergy",
      5: "Caution",
      6: "Synergy",
      7: "Caution",
      8: "Synergy",
      9: "Synergy",
      10: "Synergy",
      11: "Synergy",
      12: "Dicrease",
      13: "No Synergy",
      14: "Synergy",
      15: "Synergy",
    },
  },
];
